### ISSUE TITLE
3.6: eMediplan geht nicht

### ISSUE THREAD

**Issue by rgwch** [elexis/elexis-3-base#157]
Auf einem neu installierten 3.6 geht eMediplan nicht. Beim Kloick auf das entsprechende Icon in der Medikationsöiste geschieht nichts und im Log steht:

~~~~~~~~
17:56:21.932 [main] DEBUG ch.elexis.data.Query - Executed SELECT ID FROM REZEPTE WHERE deleted='0' AND  PatientID = 'Nf6c5eba347ec7be19391' ORDER BY Datum DESC,lastupdate DESC
17:56:21.948 [main] DEBUG ch.elexis.data.Query - Executed SELECT ID FROM OUTPUT_LOG WHERE deleted='0' AND  ObjectID = 'x8ccd0383ab408bc5070' ORDER BY lastupdate DESC
17:56:21.979 [main] DEBUG ch.elexis.data.Query - Executed SELECT ID FROM OUTPUT_LOG WHERE deleted='0' AND  ObjectID = 'td7e4d5b553a78a70404' ORDER BY lastupdate DESC
17:56:22.042 [main] DEBUG ch.elexis.data.Query - Executed SELECT ID FROM LEISTUNGEN WHERE deleted='0' AND  Behandlung = 'Qafea421f16d8281221526' ORDER BY Klasse,Leistg_code
17:56:23.073 [main] DEBUG c.e.c.u.a.GlobalEventDispatcher - partHidden ch.elexis.core.ui.views.KonsDetailView@599100
17:56:23.073 [main] DEBUG c.e.c.u.a.GlobalEventDispatcher - Calling partHidden listener ch.elexis.core.ui.views.KonsDetailView@599100
17:56:23.182 [main] DEBUG c.e.c.u.a.GlobalEventDispatcher - partVisible ch.elexis.core.ui.medication.views.MedicationView@2c087e
17:56:23.261 [main] DEBUG ch.elexis.data.Query - Executed SELECT ID, DateUntil, RezeptID, prescType, Artikel FROM PATIENT_ARTIKEL_JOINT WHERE deleted='0' AND  PatientID = 'Nf6c5eba347ec7be19391'
17:56:23.292 [main] DEBUG ch.elexis.data.Query - Executed SELECT ID, DateFrom, DateUntil, RezeptID, prescType, Artikel FROM PATIENT_ARTIKEL_JOINT WHERE deleted='0' AND  PatientID = 'Nf6c5eba347ec7be19391' ORDER BY DateFrom DESC
17:56:23.292 [pool-6-thread-1] DEBUG ch.elexis.data.Query - Executed SELECT ID FROM PATIENT_ARTIKEL_JOINT WHERE deleted='0' AND  PatientID = 'Nf6c5eba347ec7be19391' AND  Artikel = 'ch.artikelstamm.elexis.common.ArtikelstammItem::0768065958003564870320188' AND  RezeptID <> '' ORDER BY lastupdate DESC
17:56:23.292 [pool-6-thread-1] DEBUG ch.elexis.data.Query - Executed SELECT ID FROM PATIENT_ARTIKEL_JOINT WHERE deleted='0' AND  PatientID = 'Nf6c5eba347ec7be19391' AND  Artikel = 'ch.artikelstamm.elexis.common.ArtikelstammItem::0768065958003564870320188' AND  RezeptID <> 'Direktabgabe' AND  RezeptID <> '' ORDER BY lastupdate DESC
17:56:23.308 [pool-6-thread-1] DEBUG ch.elexis.data.Query - Executed SELECT ID FROM USER_ WHERE deleted='0' AND  KONTAKT_ID = 'Lf68adc9d4f9578d0b348'
17:56:32.403 [Timer-1] DEBUG ch.elexis.data.Query - Executed SELECT ID FROM CH_ELEXIS_MESSAGES WHERE deleted='0' AND  destination = 'Lf68adc9d4f9578d0b348'
17:56:32.746 [main] DEBUG ch.elexis.data.Query - Executed SELECT ID, DateUntil, RezeptID, prescType, Artikel FROM PATIENT_ARTIKEL_JOINT WHERE deleted='0' AND  PatientID = 'Nf6c5eba347ec7be19391'
17:56:32.746 [main] DEBUG ch.elexis.data.Query - Executed SELECT ID, DateUntil, RezeptID, prescType, Artikel FROM PATIENT_ARTIKEL_JOINT WHERE deleted='0' AND  PatientID = 'Nf6c5eba347ec7be19391'
17:56:32.746 [main] DEBUG ch.elexis.data.Query - Executed SELECT ID, DateUntil, RezeptID, prescType, Artikel FROM PATIENT_ARTIKEL_JOINT WHERE deleted='0' AND  PatientID = 'Nf6c5eba347ec7be19391'
17:56:32.762 [main] DEBUG ch.elexis.data.Query - Executed SELECT ID FROM PATIENT_ARTIKEL_JOINT WHERE deleted='0' AND  PatientID = 'Nf6c5eba347ec7be19391' AND  Artikel = 'ch.artikelstamm.elexis.common.ArtikelstammItem::0768065958003564870320188' AND  RezeptID <> '' ORDER BY lastupdate DESC
17:56:32.762 [main] DEBUG ch.elexis.data.Query - Executed SELECT ID FROM PATIENT_ARTIKEL_JOINT WHERE deleted='0' AND  PatientID = 'Nf6c5eba347ec7be19391' AND  Artikel = 'ch.artikelstamm.elexis.common.ArtikelstammItem::0768065958003564870320188' AND  RezeptID <> 'Direktabgabe' AND  RezeptID <> '' ORDER BY lastupdate DESC
17:56:32.762 [main] DEBUG ch.elexis.data.Query - Executed SELECT ID FROM USER_ WHERE deleted='0' AND  KONTAKT_ID = 'Lf68adc9d4f9578d0b348'
17:56:32.778 [main] DEBUG ch.elexis.data.Query - Executed SELECT ID FROM XID WHERE deleted='0' AND  object = 'mdaa695a5bb85e21d20f25' AND  domain = 'www.xid.ch/id/ean'
17:56:32.809 [main] DEBUG ch.elexis.data.Query - Executed SELECT ID FROM XID WHERE deleted='0' AND  object = 'Lf68adc9d4f9578d0b348' AND  domain = 'www.xid.ch/id/ean'
17:56:32.887 [main] ERROR c.e.c.a.a.ApplicationWorkbenchAdvisor - Nicht abgefangene EventLoop-Exception!java.lang.IllegalStateException: No IFormattedOutputFactory available
org.eclipse.e4.core.di.InjectionException: java.lang.IllegalStateException: No IFormattedOutputFactory available
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:65) ~[na:na]
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:305) ~[na:na]
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:239) ~[na:na]
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132) ~[na:na]
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152) ~[na:na]
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494) ~[na:na]
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487) ~[na:na]
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210) ~[na:na]
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:431) ~[na:na]
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:446) ~[na:na]
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:472) ~[na:na]
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86) ~[na:na]
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428) ~[na:na]
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079) ~[na:na]
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238) ~[na:na]
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817) ~[na:na]
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150) ~[na:na]
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336) ~[na:na]
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039) ~[na:na]
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153) ~[na:na]
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680) ~[na:na]
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336) ~[na:na]
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594) ~[na:na]
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148) ~[na:na]
	at ch.elexis.core.application.Desk.start(Desk.java:121) ~[na:na]
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196) ~[na:na]
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134) ~[na:na]
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104) ~[na:na]
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388) ~[na:na]
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_181]
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653) ~[org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar:na]
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590) ~[org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar:na]
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499) ~[org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar:na]
Caused by: java.lang.IllegalStateException: No IFormattedOutputFactory available
	at at.medevit.elexis.emediplan.core.internal.EMediplanServiceImpl.createPdf(EMediplanServiceImpl.java:128) ~[na:na]
	at at.medevit.elexis.emediplan.core.internal.EMediplanServiceImpl.lambda$1(EMediplanServiceImpl.java:105) ~[na:na]
	at java.util.Optional.ifPresent(Unknown Source) ~[na:1.8.0_181]
	at at.medevit.elexis.emediplan.core.internal.EMediplanServiceImpl.exportEMediplanPdf(EMediplanServiceImpl.java:104) ~[na:na]
	at at.medevit.elexis.emediplan.ui.handler.CreateAndOpenHandler.execute(CreateAndOpenHandler.java:75) ~[na:na]
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:291) ~[na:na]
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:92) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_181]
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55) ~[na:na]
	... 36 common frames omitted
17:56:32.887 [main] ERROR PLATFORM - [org.eclipse.core.runtime] Unhandled event loop exception
org.eclipse.e4.core.di.InjectionException: java.lang.IllegalStateException: No IFormattedOutputFactory available
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:65) ~[na:na]
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:305) ~[na:na]
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:239) ~[na:na]
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132) ~[na:na]
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152) ~[na:na]
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494) ~[na:na]
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487) ~[na:na]
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210) ~[na:na]
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:431) ~[na:na]
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:446) ~[na:na]
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:472) ~[na:na]
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86) ~[na:na]
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428) ~[na:na]
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079) ~[na:na]
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238) ~[na:na]
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817) ~[na:na]
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150) ~[na:na]
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336) ~[na:na]
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039) ~[na:na]
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153) ~[na:na]
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680) ~[na:na]
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336) ~[na:na]
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594) ~[na:na]
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148) ~[na:na]
	at ch.elexis.core.application.Desk.start(Desk.java:121) ~[na:na]
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196) ~[na:na]
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134) ~[na:na]
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104) ~[na:na]
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388) ~[na:na]
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_181]
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653) ~[org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar:na]
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590) ~[org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar:na]
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499) ~[org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar:na]
Caused by: java.lang.IllegalStateException: No IFormattedOutputFactory available
	at at.medevit.elexis.emediplan.core.internal.EMediplanServiceImpl.createPdf(EMediplanServiceImpl.java:128) ~[na:na]
	at at.medevit.elexis.emediplan.core.internal.EMediplanServiceImpl.lambda$1(EMediplanServiceImpl.java:105) ~[na:na]
	at java.util.Optional.ifPresent(Unknown Source) ~[na:1.8.0_181]
	at at.medevit.elexis.emediplan.core.internal.EMediplanServiceImpl.exportEMediplanPdf(EMediplanServiceImpl.java:104) ~[na:na]
	at at.medevit.elexis.emediplan.ui.handler.CreateAndOpenHandler.execute(CreateAndOpenHandler.java:75) ~[na:na]
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:291) ~[na:na]
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:92) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_181]
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55) ~[na:na]
	... 36 common frames omitted
17:56:32.903 [ch.elexis.core.logging.osgi.OsgiSl4fjLoggingAdapter@1b11453] ERROR OSGI - [org.eclipse.ui.workbench] Unhandled event loop exception
org.eclipse.e4.core.di.InjectionException: java.lang.IllegalStateException: No IFormattedOutputFactory available
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:65) ~[na:na]
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:305) ~[na:na]
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:239) ~[na:na]
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132) ~[na:na]
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152) ~[na:na]
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494) ~[na:na]
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487) ~[na:na]
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210) ~[na:na]
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:431) ~[na:na]
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:446) ~[na:na]
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:472) ~[na:na]
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86) ~[na:na]
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428) ~[na:na]
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079) ~[na:na]
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238) ~[na:na]
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817) ~[na:na]
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150) ~[na:na]
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336) ~[na:na]
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039) ~[na:na]
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153) ~[na:na]
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680) ~[na:na]
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336) ~[na:na]
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594) ~[na:na]
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148) ~[na:na]
	at ch.elexis.core.application.Desk.start(Desk.java:121) ~[na:na]
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196) ~[na:na]
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134) ~[na:na]
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104) ~[na:na]
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388) ~[na:na]
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_181]
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653) ~[org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar:na]
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590) ~[org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar:na]
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499) ~[org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar:na]
Caused by: java.lang.IllegalStateException: No IFormattedOutputFactory available
	at at.medevit.elexis.emediplan.core.internal.EMediplanServiceImpl.createPdf(EMediplanServiceImpl.java:128) ~[na:na]
	at at.medevit.elexis.emediplan.core.internal.EMediplanServiceImpl.lambda$1(EMediplanServiceImpl.java:105) ~[na:na]
	at java.util.Optional.ifPresent(Unknown Source) ~[na:1.8.0_181]
	at at.medevit.elexis.emediplan.core.internal.EMediplanServiceImpl.exportEMediplanPdf(EMediplanServiceImpl.java:104) ~[na:na]
	at at.medevit.elexis.emediplan.ui.handler.CreateAndOpenHandler.execute(CreateAndOpenHandler.java:75) ~[na:na]
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:291) ~[na:na]
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:92) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_181]
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55) ~[na:na]
	... 36 common frames omitted
~~~~~~~~

**Comment by col-panic** [comment]
Interessant, hier schein ein entsprechendes Output-Plugin zu fehlen. Dieser wird über den FOP Service bereitgestellt. Kannst du verifizieren, dass der FOP Wrapper installiert ist?

**Comment by ngiger** [comment]
@rgwch: Hast Du das Problem nach diesen Patch immer noch? Wenn nicht, bitte issue schliessen

**Comment by rgwch** [comment]
@ngigier Mit 3.7 funktionert er wieder (getestet mit Ubuntu)
