### ISSUE TITLE
Hilotec Text Plugin

### ISSUE THREAD

**Issue by rgwch** [elexis/elexis-3-base#169]
Beim Hilotec Text Plugin bewirkt keiner der Knöpfe irgend etwas. Es wird weder ein Dokument geöffnet noch der Editor gestartet.

Umgebung: Windows 7,  from Scratch installiertes Elexis 3.5 von hier: http://download.elexis.info/elexis/3.5/products/, vom vorkonfigurierten Base-Repository installiertes Hilotec Trxt Plugin

(Und übrigens ist da das Privatrechnungs-Plugin in die Kategorie Dokumentenverwaltung gerutscht)

Im Log steht:

~~~~
javax.xml.parsers.FactoryConfigurationError: Provider org.apache.xerces.jaxp.SAXParserFactoryImpl not found
	at javax.xml.parsers.SAXParserFactory.newInstance(Unknown Source) ~[na:1.8.0_191]
	at org.odftoolkit.odfdom.doc.OdfDocument.getFileDom(OdfDocument.java:1155) ~[na:na]
	at org.odftoolkit.odfdom.doc.OdfDocument.getContentDom(OdfDocument.java:747) ~[na:na]
	at org.odftoolkit.odfdom.doc.OdfDocument.insertDOMsToPkg(OdfDocument.java:940) ~[na:na]
	at org.odftoolkit.odfdom.doc.OdfDocument.save(OdfDocument.java:846) ~[na:na]
	at com.hilotec.elexis.opendocument.TextPlugin.odtSync(TextPlugin.java:350) ~[na:na]
	at com.hilotec.elexis.opendocument.TextPlugin.closeFile(TextPlugin.java:611) ~[na:na]
	at com.hilotec.elexis.opendocument.TextPlugin.loadFromStream(TextPlugin.java:686) ~[na:na]
	at com.hilotec.elexis.opendocument.TextPlugin.loadFromByteArray(TextPlugin.java:675) ~[na:na]
	at ch.elexis.core.ui.text.TextContainer.open(TextContainer.java:984) ~[na:na]
	at ch.elexis.core.ui.views.TextView.openDocument(TextView.java:133) ~[na:na]
	at ch.elexis.core.ui.views.BriefAuswahl$6.run(BriefAuswahl.java:504) ~[na:na]
	at ch.elexis.core.ui.views.BriefAuswahl$2.doubleClicked(BriefAuswahl.java:167) ~[na:na]
	at ch.elexis.core.ui.util.viewers.CommonViewer.doubleClick(CommonViewer.java:396) ~[na:na]
	at org.eclipse.jface.viewers.StructuredViewer$1.run(StructuredViewer.java:833) ~[na:na]
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42) ~[na:na]
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50) ~[na:na]
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173) ~[na:na]
	at org.eclipse.jface.viewers.StructuredViewer.fireDoubleClick(StructuredViewer.java:830) ~[na:na]
	at org.eclipse.jface.viewers.StructuredViewer.handleDoubleSelect(StructuredViewer.java:1151) ~[na:na]
	at org.eclipse.jface.viewers.StructuredViewer$4.widgetDefaultSelected(StructuredViewer.java:1264) ~[na:na]
	at org.eclipse.jface.util.OpenStrategy.fireDefaultSelectionEvent(OpenStrategy.java:252) ~[na:na]
	at org.eclipse.jface.util.OpenStrategy.access$0(OpenStrategy.java:249) ~[na:na]
	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:311) ~[na:na]
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84) ~[na:na]
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4418) ~[na:na]
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079) ~[na:na]
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4236) ~[na:na]
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3824) ~[na:na]
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121) ~[na:na]
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336) ~[na:na]
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022) ~[na:na]
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150) ~[na:na]
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693) ~[na:na]
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336) ~[na:na]
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610) ~[na:na]
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148) ~[na:na]
	at ch.elexis.core.application.Desk.start(Desk.java:121) ~[na:na]
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196) ~[na:na]
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134) ~[na:na]
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104) ~[na:na]
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388) ~[na:na]
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_191]
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673) ~[org.eclipse.equinox.launcher_1.3.201.v20161025-1711.jar:na]
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610) ~[org.eclipse.equinox.launcher_1.3.201.v20161025-1711.jar:na]
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519) ~[org.eclipse.equinox.launcher_1.3.201.v20161025-1711.jar:na]
~~~~

**Comment by ngiger** [comment]
Hallo Gerry

On Mittwoch, 5. Dezember 2018 05:42:28 CET rgwch wrote:
> (Und übrigens ist da das Privatrechnungs-Plugin in die Kategorie
> Dokumentenverwaltung gerutscht)
Danke für den Hinweis. Dies ist geflickt mit
https://github.com/elexis/elexis-3-base/commit/f3855178860eef3ef613407ad3a6c4362b299aee

Das Problem mit dem Hilotec Text Plugin werde ich nächste Woche anschauen.

Liebe Grüsse

Niklaus

-- 
Niklaus Giger
Wieshoschet 6
CH-8753 Mollis
+41  (0)55 612 20 54 P
+41  (0)77 454 01 61 Mobil

**Comment by rgwch** [comment]
@ngiger Habe das jetzt nochmal versucht zu installieren. Diesmal mit dem neuesten Elexis (3.7) unter Windows 10-64 und mit OpenOffice 4.1.6.

Passiert weiterhin nichts wirklich sichtbares

Haben die Medelexis Kunden denn alle auf Microsoft Word umgestellt?

~~~
11:33:32.669 [main] DEBUG c.e.core.data.lock.LocalLockService - Acquiring lock on [ch.elexis.data.Brief@63b2450b]
11:33:32.669 [main] DEBUG ch.elexis.core.ui.text.TextContainer - ch.elexis.views/TextContainer.java open(final Brief brief): begin - brief==ch.elexis.data.Brief@63b2450b: Anmeldung Herrmann
11:33:32.669 [main] DEBUG ch.elexis.core.ui.text.TextContainer - ch.elexisviews/TextContainer.java.open(): brief.getLabel())==29.01.2018 Anmeldung Herrmann
11:33:32.678 [main] DEBUG ch.elexis.core.ui.text.TextContainer - ch.elexisviews/TextContainer.java.open(): about to byte[] arr = brief.loadBinary()...
11:33:32.775 [main] DEBUG ch.elexis.core.ui.text.TextContainer - ch.elexis.views/TextContainer.java open(): about to return plugin.loadFromByteArray(arr, false) and end...
11:33:32.775 [main] INFO  com.hilotec.elexis.opendocument - loadFromByteArray: asTemplate false
11:33:32.775 [main] INFO  com.hilotec.elexis.opendocument - loadFromStream: false
11:33:32.775 [main] INFO  com.hilotec.elexis.opendocument - ensureClosed: Armeswesen Testperson
11:33:32.791 [main] INFO  com.hilotec.elexis.opendocument - loadFromStream: C:\Users\Gerry\AppData\Local\Temp\1_Testperson_Armeswesen_2019_01_14_11_33_32_7757592628154722286353.odt
11:33:33.041 [main] ERROR PLATFORM - [org.eclipse.core.runtime] Problems occurred when invoking code from plug-in: "org.eclipse.jface".
java.lang.VerifyError: (class: org/odftoolkit/odfdom/pkg/OdfPackage, method: getDom signature: (Ljava/lang/String;)Lorg/w3c/dom/Document;) Incompatible object argument for function call
	at org.odftoolkit.odfdom.doc.OdfDocument.loadDocument(OdfDocument.java:331) ~[na:na]
	at com.hilotec.elexis.opendocument.TextPlugin.loadFromStream(TextPlugin.java:691) ~[na:na]
	at com.hilotec.elexis.opendocument.TextPlugin.loadFromByteArray(TextPlugin.java:672) ~[na:na]
	at ch.elexis.core.ui.text.TextContainer.open(TextContainer.java:984) ~[na:na]
	at ch.elexis.core.ui.views.TextView.openDocument(TextView.java:133) ~[na:na]
	at ch.elexis.core.ui.views.BriefAuswahl$6.run(BriefAuswahl.java:504) ~[na:na]
	at ch.elexis.core.ui.views.BriefAuswahl$2.doubleClicked(BriefAuswahl.java:167) ~[na:na]
	at ch.elexis.core.ui.util.viewers.CommonViewer.doubleClick(CommonViewer.java:404) ~[na:na]
	at org.eclipse.jface.viewers.StructuredViewer$1.run(StructuredViewer.java:831) ~[org.eclipse.jface_3.13.2.v20171022-1656.jar:na]
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42) ~[org.eclipse.equinox.common_3.9.0.v20170207-1454.jar:na]
	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:44) [org.eclipse.ui.workbench_3.110.1.v20170704-1208.jar:na]
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173) ~[org.eclipse.jface_3.13.2.v20171022-1656.jar:na]
	at org.eclipse.jface.viewers.StructuredViewer.fireDoubleClick(StructuredViewer.java:828) ~[org.eclipse.jface_3.13.2.v20171022-1656.jar:na]
	at org.eclipse.jface.viewers.StructuredViewer.handleDoubleSelect(StructuredViewer.java:1145) ~[org.eclipse.jface_3.13.2.v20171022-1656.jar:na]
	at org.eclipse.jface.viewers.StructuredViewer$4.widgetDefaultSelected(StructuredViewer.java:1258) ~[org.eclipse.jface_3.13.2.v20171022-1656.jar:na]
	at org.eclipse.jface.util.OpenStrategy.fireDefaultSelectionEvent(OpenStrategy.java:249) ~[org.eclipse.jface_3.13.2.v20171022-1656.jar:na]
	at org.eclipse.jface.util.OpenStrategy.access$0(OpenStrategy.java:247) ~[org.eclipse.jface_3.13.2.v20171022-1656.jar:na]
	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:306) ~[org.eclipse.jface_3.13.2.v20171022-1656.jar:na]
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86) ~[org.eclipse.swt.win32.win32.x86_64_3.106.3.v20180329-0507.jar:na]
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428) ~[org.eclipse.swt.win32.win32.x86_64_3.106.3.v20180329-0507.jar:na]
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079) ~[org.eclipse.swt.win32.win32.x86_64_3.106.3.v20180329-0507.jar:na]
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238) ~[org.eclipse.swt.win32.win32.x86_64_3.106.3.v20180329-0507.jar:na]
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817) ~[org.eclipse.swt.win32.win32.x86_64_3.106.3.v20180329-0507.jar:na]
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150) ~[org.eclipse.e4.ui.workbench.swt_0.14.101.v20170710-1119.jar:na]
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336) ~[org.eclipse.core.databinding.observable_1.6.100.v20170515-1119.jar:na]
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039) ~[org.eclipse.e4.ui.workbench.swt_0.14.101.v20170710-1119.jar:na]
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153) ~[org.eclipse.e4.ui.workbench_1.5.1.v20170815-1446.jar:na]
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680) ~[org.eclipse.ui.workbench_3.110.1.v20170704-1208.jar:na]
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336) ~[org.eclipse.core.databinding.observable_1.6.100.v20170515-1119.jar:na]
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594) ~[org.eclipse.ui.workbench_3.110.1.v20170704-1208.jar:na]
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148) ~[org.eclipse.ui.workbench_3.110.1.v20170704-1208.jar:na]
	at ch.elexis.core.application.Desk.start(Desk.java:121) ~[na:na]
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196) ~[org.eclipse.equinox.app_1.3.400.v20150715-1528.jar:na]
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134) ~[org.eclipse.osgi_3.12.100.v20180210-1608.jar:na]
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104) ~[org.eclipse.osgi_3.12.100.v20180210-1608.jar:na]
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388) ~[org.eclipse.osgi_3.12.100.v20180210-1608.jar:na]
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243) ~[org.eclipse.osgi_3.12.100.v20180210-1608.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_191]
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653) ~[org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar:na]
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590) ~[org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar:na]
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499) ~[org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar:na]
11:33:33.041 [ch.elexis.core.logging.osgi.OsgiSl4fjLoggingAdapter@4d493ac8] ERROR OSGI - [org.eclipse.jface] Problems occurred when invoking code from plug-in: "org.eclipse.jface".
java.lang.VerifyError: (class: org/odftoolkit/odfdom/pkg/OdfPackage, method: getDom signature: (Ljava/lang/String;)Lorg/w3c/dom/Document;) Incompatible object argument for function call
	at org.odftoolkit.odfdom.doc.OdfDocument.loadDocument(OdfDocument.java:331) ~[na:na]
	at com.hilotec.elexis.opendocument.TextPlugin.loadFromStream(TextPlugin.java:691) ~[na:na]
	at com.hilotec.elexis.opendocument.TextPlugin.loadFromByteArray(TextPlugin.java:672) ~[na:na]
	at ch.elexis.core.ui.text.TextContainer.open(TextContainer.java:984) ~[na:na]
	at ch.elexis.core.ui.views.TextView.openDocument(TextView.java:133) ~[na:na]
	at ch.elexis.core.ui.views.BriefAuswahl$6.run(BriefAuswahl.java:504) ~[na:na]
	at ch.elexis.core.ui.views.BriefAuswahl$2.doubleClicked(BriefAuswahl.java:167) ~[na:na]
	at ch.elexis.core.ui.util.viewers.CommonViewer.doubleClick(CommonViewer.java:404) ~[na:na]
	at org.eclipse.jface.viewers.StructuredViewer$1.run(StructuredViewer.java:831) ~[na:na]
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42) ~[na:na]
	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:44) ~[na:na]
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173) ~[na:na]
	at org.eclipse.jface.viewers.StructuredViewer.fireDoubleClick(StructuredViewer.java:828) ~[na:na]
	at org.eclipse.jface.viewers.StructuredViewer.handleDoubleSelect(StructuredViewer.java:1145) ~[na:na]
	at org.eclipse.jface.viewers.StructuredViewer$4.widgetDefaultSelected(StructuredViewer.java:1258) ~[na:na]
	at org.eclipse.jface.util.OpenStrategy.fireDefaultSelectionEvent(OpenStrategy.java:249) ~[na:na]
	at org.eclipse.jface.util.OpenStrategy.access$0(OpenStrategy.java:247) ~[na:na]
	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:306) ~[na:na]
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86) ~[na:na]
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428) ~[na:na]
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079) ~[na:na]
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238) ~[na:na]
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817) ~[na:na]
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150) ~[na:na]
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336) ~[na:na]
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039) ~[na:na]
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153) ~[na:na]
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680) ~[na:na]
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336) ~[na:na]
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594) ~[na:na]
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148) ~[na:na]
	at ch.elexis.core.application.Desk.start(Desk.java:121) ~[na:na]
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196) ~[na:na]
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134) ~[na:na]
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104) ~[na:na]
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388) ~[na:na]
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_191]
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653) ~[org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar:na]
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590) ~[org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar:na]
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499) ~[org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar:na]
~~~

**Comment by ngiger** [comment]
Das Testen vom Hilotec ODF-Plugin ist auf meiner ToDo-Liste für die rcptt tests.
Kannst Du mir Deinen Testfall noch etwas genauer beschreiben?
Am liebsten wäre es mir, wenn Du Dich soweit in RCPTT einarbeitest, damit Du ab einer jungfräulichen demoDB von http://download.elexis.info/demoDB/ alle Schritte aufzeichnest. Ich helfe Dir gerne dabei, wenn Du über etwas stolperst.
Du solltest meiner Meinung nach mehr als 1h brauchen, um via https://github.com/elexis/elexis-uitest#neue-testf%C3%A4lle-erstellent durchzuarbeiten. Danach könntest Du mir die aufgezeichneten Test schicken und ich würde diese als Basis für meine Tests nehmen.

**Comment by rgwch** [comment]
Testfall: 

* Neu installiertes Windows 10 Pro 64Bit in einer VirtualBox VM (Keine Raubkopie, ich habe legale Lizenzen, weil auf den Praxis PC's immer ungefragt Windows 10 vorinstalliert ist, das ich umgehend lösche und höchstens noch in einer VM reinstalliere ...). die VM hat 2 Kerne eines Core-i7-6700 und 5 GB Arbeitsspeicher zugeordnet

* JDK 8 64 Bit installieren

* Elexis 3.7 64 Bit von hier http://download.elexis.info/elexis/3.7/products/ herunterladen und installieren

* OpenOffice 4.1.6 installieren

* Elexis starten, mit der Datrenbank verbinden. Unter Hilfe-Neue Software installieren das Hilotec Plugin installieren und ELexis neu starten.

* unter Datei-Einstellungen dem Hilotec-Opendocument Plugin den Pfad zu swriter.exe angeben. Alle anderen Felder liess ich leer.

* Einen Patienten auswählen, die Briefe-View öffnen. Dort sind zwei Buttons (Editor öffnen und Datei importieren). Egal auf welchen man klickt, es passiert nichts. Wenn man versucht, ein existierendes Dokument zu öffnen, erscheint eine Fehlerbox: "Ein Fehler ist aufgetreten, Details finden Sie im Fehlerprotokoll". Dort steht das, was ich oben gepostet habe.

Aus meiner Sicht müsste der Fehler leicht zu reproduzieren sein, da er bei mir bisher immer auftritt, sowohl unter 32Bit Windows 7 als auch unter 64-Bit Windows 10, und sowieso unter Linux. Wenn er bei Euch nicht auftritt, dann wäre ich sehr dankbar für Beschreibung einer Systemumgebung, in der das Plugin funktioniert. 

RCPTT schaue ich mir bei Gelegenheit gerne an.
