### ISSUE TITLE
PDFBills throws unhelpful exception

### ISSUE THREAD

**Issue by ngiger** [elexis/elexis-3-base#249]
An Elexis OpenSource practice trying to migrate to Elexis 3.9 ran into the following unhelpful error
![burlein_fehler](https://user-images.githubusercontent.com/265800/196621017-f7d72109-0fe9-4c9d-88df-c9c1cf21261c.png)
In the log I found
[elexis-3.log](https://github.com/elexis/elexis-3-base/files/9817735/elexis-3.log)

The relevant piece is
```
11:51:01.184 [main] ERROR c.elexis.pdfBills.ElexisPDFGenerator - Error outputting bill
java.lang.IllegalStateException: No IFormattedOutput implementation available
	at ch.elexis.pdfBills.ElexisPDFGenerator.generatePdf(ElexisPDFGenerator.java:257)
	at ch.elexis.pdfBills.ElexisPDFGenerator.generateQrPatBill(ElexisPDFGenerator.java:481)
	at ch.elexis.pdfBills.ElexisPDFGenerator.printQrBill(ElexisPDFGenerator.java:460)
	at ch.elexis.pdfBills.QrRnOutputter$1.run(QrRnOutputter.java:168)
```
It looks to me that the pdfbill feature should include the fop wrapper, too

**Comment by ngiger** [comment]
Fixed with https://github.com/elexis/elexis-3-base/pull/250 and backported to 3.9
